version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/cargo-clippy"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci(cargo-clippy)"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/cargo-test-coverage"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci(cargo-test-coverage)"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/cargo-doc-pages"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci(cargo-doc-pages)"
    open-pull-requests-limit: 10
